output "master_node_name" {
  value       = hyperv_machine_instance.master.name
  description = "Hostname of the Kubernetes master node"
}

output "master_node_ip" {
  value       = var.master_node.ip
  description = "Static IP address of the Kubernetes master node"
}

output "worker_node_ips" {
  value = {
    for k, v in var.worker_nodes : k => v.ip
  }
  description = "Static IP addresses of the Kubernetes worker nodes"
}

output "private_switch_name" {
  value       = hyperv_network_switch.private_switch.name
  description = "Name of the Hyper-V private virtual switch"
}

output "public_switch_name" {
  value       = hyperv_network_switch.public_switch.name
  description = "Name of the Hyper-V public virtual switch"
}

# -----------------------------------------------------------------------------
# Dynamic Generation of Ansible Inventory File
# -----------------------------------------------------------------------------

resource "local_file" "ansible_inventory" {
  content = <<-EOT
# =============================================================================
# Dynamically Generated Ansible Inventory for K3s Kubernetes Cluster
# Generated by Terraform (Hyper-V Provisioner)
# =============================================================================

[masters]
${var.master_node.name} ansible_host=${var.master_node.ip} ansible_user=ubuntu node_type=master

[workers]
%{ for name, config in var.worker_nodes ~}
${name} ansible_host=${config.ip} ansible_user=ubuntu node_type=worker
%{ endfor ~}

[k8s_cluster:children]
masters
workers

[k8s_cluster:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
master_ip=${var.master_node.ip}
k3s_version=v1.28.5+k3s1
containerd_config_path=/etc/containerd/config.toml
EOT

  filename = "${path.module}/../../ansible/inventory/hosts.ini"
}
