cat << 'EOF' > inventory.ini
[master]
desktop-worker ansible_connection=local ansible_python_interpreter=/usr/bin/python3.13

[workers]
desktop-worker2 ansible_connection=local ansible_python_interpreter=/usr/bin/python3.13
desktop-worker3 ansible_connection=local ansible_python_interpreter=/usr/bin/python3.13
EOF