[master]
Master ansible_host=172.17.46.177 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3

[workers]
Worker-1 ansible_host=172.17.39.97 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3
Worker-2 ansible_host=172.17.35.160 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3