"""Single-pass, deterministic PII redaction/tokenization helpers."""
from __future__ import annotations

import hashlib
import hmac
import re
from typing import Any, Dict, Tuple


_EMAIL = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}"
_PHONE = r"\+?\d[\d ()-]{7,}\d"
_CARD = r"(?:\d[ -]?){13,19}"
_SSN = r"\d{3}-\d{2}-\d{4}"
_DATETIME = r"\d{4}-\d{2}-\d{2}(?:[T\s]\d{2}:\d{2}(?::\d{2}(?:\.\d{1,6})?)?(?:Z|[+-]\d{2}:?\d{2})?)?"

# One alternation gives each source character at most one chance to be
# classified. This prevents a replacement token from being processed by a
# later pattern and makes the precedence explicit.
PII_PATTERN = re.compile(
    rf"(?P<datetime>(?<!\d){_DATETIME}(?!\d))"
    rf"|(?P<ssn>(?<!\d){_SSN}(?!\d))"
    rf"|(?P<card>(?<!\d){_CARD}(?!\d))"
    rf"|(?P<email>\b{_EMAIL}\b)"
    rf"|(?P<phone>(?<!\w){_PHONE}(?!\w))",
    re.IGNORECASE,
)

# These fields either contain caller-provided identifiers or free-form content.
# They must not cross an audit or event boundary in cleartext.  Server-issued
# correlation fields are deliberately *not* included: they are the only stable
# identifiers retained for traceability.
_BOUNDARY_SECRET_FIELDS = {
    "answer",
    "chunk",
    "chunks",
    "content",
    "document",
    "merchant",
    "merchant_id",
    "output",
    "payment_identifier",
    "prompt",
    "question",
    "retrieved",
    "retrieved_chunks",
    "source",
    "text",
    "transaction",
    "transaction_id",
}
# These values are generated by the service and are intentionally retained as
# the audit/event correlation contract.  They resemble phone/card patterns
# often enough that they must be excluded before generic regex redaction.
_SERVER_IDENTIFIER_FIELDS = {
    "audit_key",
    "causation_id",
    "chunk_id",
    "correlation_id",
    "entity_id",
    "event_id",
    "object_key",
    "operation_id",
    "request_id",
    "traceparent",
}
_TOKEN_VERSION = "V1"
_TOKEN = re.compile(r"^<PII_[A-Z0-9_]+_V1_[0-9a-f]{32}>$")


def _is_luhn_valid(value: str) -> bool:
    digits = [int(character) for character in value if character.isdigit()]
    if not 13 <= len(digits) <= 19:
        return False
    total = 0
    for index, digit in enumerate(reversed(digits)):
        if index % 2:
            digit *= 2
            if digit > 9:
                digit -= 9
        total += digit
    return total % 10 == 0


class PIIRedactor:
    """Application-facing redactor; keeps the HMAC key in configuration."""

    def __init__(self, salt: str) -> None:
        if not salt:
            raise ValueError("PII token key must not be empty")
        self.salt = salt

    def redact(self, text: str) -> Tuple[str, Dict[str, int]]:
        return redact(text, self.salt)

    def sanitize_for_boundary(self, value: Any, field_name: str = "") -> Any:
        return sanitize_for_boundary(value, self.salt, field_name)


def token_for(kind: str, value: str, salt: str) -> str:
    """Create a stable 128-bit HMAC token without exposing the source value."""
    normalized_kind = kind.lower()
    normalized_value = _canonicalize(normalized_kind, value)
    digest = hmac.new(
        salt.encode("utf-8"),
        f"{_TOKEN_VERSION}:{normalized_kind}:{normalized_value}".encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()[:32]
    return f"<PII_{kind.upper()}_{_TOKEN_VERSION}_{digest}>"


def _canonicalize(kind: str, value: str) -> str:
    """Normalize equivalent PII representations before HMAC tokenization."""
    value = value.strip()
    if kind == "email":
        return value.lower()
    if kind in {"phone", "card", "ssn"}:
        return "".join(character for character in value if character.isdigit())
    return value


def sanitize_for_boundary(value: Any, salt: str, field_name: str = "") -> Any:
    """Return a representation safe for audit and event publication.

    Free-form content and caller-supplied identifiers are deterministically
    HMAC-tokenized as a whole.  Other strings are still pattern-redacted to
    catch PII that appears in an unexpected field.  This function is a defense
    in depth guard; the RAG routes must still tokenize at their entry boundary
    before data reaches retrieval or downstream publishers.
    """
    if isinstance(value, dict):
        return {
            str(key): sanitize_for_boundary(item, salt, str(key))
            for key, item in value.items()
        }
    if isinstance(value, (list, tuple)):
        return [sanitize_for_boundary(item, salt, field_name) for item in value]
    if not isinstance(value, str):
        return value
    if not value:
        return value
    if _TOKEN.fullmatch(value):
        return value

    normalized_name = field_name.lower().removesuffix("_token")
    if normalized_name in _SERVER_IDENTIFIER_FIELDS:
        return value
    if normalized_name in _BOUNDARY_SECRET_FIELDS:
        kind = re.sub(r"[^a-z0-9]+", "_", normalized_name).strip("_") or "value"
        return token_for(kind, value, salt)
    safe, _ = redact(value, salt)
    return safe


def redact(text: str, salt: str = "change-me") -> Tuple[str, Dict[str, int]]:
    counts: Dict[str, int] = {}

    def replace(match: re.Match[str]) -> str:
        kind = match.lastgroup
        value = match.group(0)
        if kind is None:
            return value
        # ISO-like timestamps satisfy the permissive phone punctuation rules
        # but are operational data, not telephone numbers.
        if kind == "datetime":
            return value
        # A 13–19 digit run is not a payment card merely because it has the
        # right length. Tokenize invalid numbers as generic numeric identifiers
        # rather than leaking them or misrepresenting them as card data.
        if kind == "card" and not _is_luhn_valid(value):
            kind = "numeric_identifier"
        counts[kind] = counts.get(kind, 0) + 1
        return token_for(kind, value, salt)

    return PII_PATTERN.sub(replace, text), counts
