{{- if .Values.chromadb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "omni-stream-RAG-mesh.fullname" . }}-chromadb-pvc
  labels:
    {{- include "omni-stream-RAG-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: chromadb
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.chromadb.persistence.size }}
{{- end }}
