apiVersion: v1
kind: Service
metadata:
  name: {{ include "omni-stream-RAG-mesh.fullname" . }}-kafka
  labels:
    {{- include "omni-stream-RAG-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  ports:
    - name: client
      port: {{ .Values.kafka.service.port }}
      targetPort: client
      protocol: TCP
    - name: controller
      port: {{ .Values.kafka.service.controllerPort }}
      targetPort: controller
      protocol: TCP
  selector:
    {{- include "omni-stream-RAG-mesh.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omni-stream-RAG-mesh.fullname" . }}-kafka-headless
  labels:
    {{- include "omni-stream-RAG-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  clusterIP: None
  ports:
    - name: client
      port: {{ .Values.kafka.service.port }}
      targetPort: client
    - name: controller
      port: {{ .Values.kafka.service.controllerPort }}
      targetPort: controller
  selector:
    {{- include "omni-stream-RAG-mesh.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
