apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omni-stream-RAG-mesh.fullname" . }}-secrets
  labels:
    {{- include "omni-stream-RAG-mesh.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | quote }}
