apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-api
  namespace: {{ .Release.Namespace }}
  {{ with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{ end }}
  labels:
    app: rag-api
    app.kubernetes.io/name: rag-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: streaming-rag-mesh
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
